### ISSUE TITLE
Running into windows setup/ dependency issues

### ISSUE THREAD

**Issue by weezywitasneezy** [fazalmajid/pingwatch#21]
**First issue I think stemmed from sqlite3 version:**

sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]      
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
       |          ^~~~~~~
.\pingwatch.go:92:34: undefined: syscall.SIGUSR1

**Resolved that by running:** 'go env -w CGO_CFLAGS="-g -O2 -Wno-return-local-addr"'

**That resulted in this error:** '.\pingwatch.go:92:34: undefined: syscall.SIGUSR1'

**Any ideas on next steps? Thanks!**

**Comment by fazalmajid** [comment]
Windows doesn't really have a notion of signals like UNIX, as it has other mechanisms. It emulates the most common ones but not more exotic ones like SIGUSR1.

You could comment out the lines:

```
        // SIGUSR1 dumps goroutines on stdout
        usr1Chan := make(chan os.Signal, 1)
        signal.Notify(usr1Chan, syscall.SIGUSR1)
        go func() {
                for {
                        <-usr1Chan
                        dump_goroutines()
                }
        }()
```

as they are only really useful for debugging purposes.

**Comment by fazalmajid** [comment]
Or alternatively build under WSL2

**Comment by weezywitasneezy** [comment]
Thank you! I was able to get it to build the pingwatch.exe 

After trying 'pingwatch -add google.com ' I'm getting this output
2023/01/10 14:30:13 adding host google.com
2023/01/10 14:30:13 could not insert host into destinationsno such table: dests

I'm guessing this is related to the sqlite

**Comment by weezywitasneezy** [comment]
After installing some sqlite extensions to VSCode I was able to successfully add a host

**Comment by weezywitasneezy** [comment]
Got it all up and running, thanks for the help!
