### ISSUE TITLE
Add option to change the default date range

### ISSUE THREAD

**Issue by fazalmajid** [fazalmajid/pingwatch#6]
By default, pingwatch shows you the last 14 days of data. For some people that might be too much, and it should be configurable.

**Comment by aslmx** [comment]
Hi, 
thanks for merging my PR :+1: 
I currently run pingwatch with interval of 10 seconds to 8 or 9 destinations.
2 days worth of data were already >100k entries in pingwatch.sqlite and had some loading time in the browser, so i decided 1day is fine for me. But the trigger is easily changeable.

Maybe the long term goal was some timeseries database like influxdb, where you have a configurable retention policies? I'm certainly no expert on this, but I could somehow plug together some systems with influxdb and grafana in the past.
(I am lucky I found the "insert into" statement in your go code so that I could know which date format you were actually using - tbh. I had never seen julian date format being used anywhere, but I knew it were no unix timestamps) 

br

**Comment by fazalmajid** [comment]
> On Sep 22, 2020, at 14:35, aslmx <notifications@github.com> wrote:
> 
> thanks for merging my PR 👍
> I currently run pingwatch with interval of 10 seconds to 8 or 9 destinations.

I was wondering how many, as I feared the legend would not scale to large numbers of destinations.

Just out of curiosity, are you using this to measure your Internet connection, or to monitor server uptime?

> 2 days worth of data were already >100k entries in pingwatch.sqlite and had some loading time in the browser, so i decided 1day is fine for me. But the trigger is easily changeable.

SQLite is not the issue, but parsing CSV in the browser probably is. I pushed an update yesterday to use Dygraph’s native format, which should speed things up, in preparation for adding the auto-refresh feature you asked for. It should be significantly snappier already. I also just added the option to change the default display window.

> Maybe the long term goal was some timeseries database like influxdb, where you have a co6*nfigurable retention policies? I'm certainly no expert on this, but I could somehow plug together some systems with influxdb and grafana in the past.

There is a new embedded DB called DuckDB that shows promise for analytic applications. It doesn’t have Go bindings yet, however. Something relatively heavyweight like InfluxDB would defeat the purpose of having a single self-contained executable small enough to run without taxing a RPi like the one I have installed in my in-laws’ closet.

> (I am lucky I found the "insert into" statement in your go code so that I could know which date format you were actually using - tbh. I had never seen julian date format being used anywhere, but I knew it were no unix timestamps)

It’s the native SQLite date/time format, such as it is. I agree it’s a rather strange choice.

**Comment by fazalmajid** [comment]
> On Sep 22, 2020, at 14:35, aslmx <notifications@github.com> wrote:
> 
> Maybe the long term goal was some timeseries database like influxdb, where you have a co6*nfigurable retention policies? I'm certainly no expert on this, but I could somehow plug together some systems with influxdb and grafana in the past.

InfluxData’s Telegraf has a ping plugin, BTW:

	https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ping

Obviously it’s a full-featured solution that can do a lot more than simply monitor ping times, but that brings along unavoidable complexity.

**Comment by aslmx** [comment]
> On Sep 22, 2020, at 14:35, aslmx ***@***.***> wrote: thanks for merging my PR +1 I currently run pingwatch with interval of 10 seconds to 8 or 9 destinations.
> I was wondering how many, as I feared the legend would not scale to large numbers of destinations. Just out of curiosity, are you using this to measure your Internet connection, or to monitor server uptime?

Both. Uptime/Reachability of two of my servers, Reachability of my DNS provider (had some issues in the past) and general connectivity.

> 2 days worth of data were already >100k entries in pingwatch.sqlite and had some loading time in the browser, so i decided 1day is fine for me. But the trigger is easily changeable.
> SQLite is not the issue, but parsing CSV in the browser probably is. I pushed an update yesterday to use Dygraph’s native format, which should speed things up, in preparation for adding the auto-refresh feature you asked for. It should be significantly snappier already. I also just added the option to change the default display window

I'm building it right now :+1: 

> Maybe the long term goal was some timeseries database like influxdb, where you have a configurable retention policies? I'm certainly no expert on this, but I could somehow plug together some systems with influxdb and grafana in the past.
> There is a new embedded DB called DuckDB that shows promise for analytic applications. It doesn’t have Go bindings yet, however. Something relatively heavyweight like InfluxDB would defeat the purpose of having a single self-contained executable small enough to run without taxing a RPi like the one I have installed in my in-laws’ closet.
Never heard of... If the libraries are either statically linked (i understand that this would then not require any dependencies for the binary, right?) or very commonly available in Distributions repository, i'm open for it - Your choice!


I heard about Telegraf, but i did not yet have the time to look further into it, but thanks for reminding me.

Thanks for your efforts!
