### ISSUE TITLE
pingwatch stopped with error message

### ISSUE THREAD

**Issue by aslmx** [fazalmajid/pingwatch#7]
Hi,

i just was checking on my ping stats and the WebUI wouldn't load.
I checked the raspberry and pingwatch has stopped with this info:

`2020/09/25 00:16:40 UNIQUE constraint failed: pings.time, pings.host ` 

Not sure how i could provide more info... pingwatch was running with -v enabled.

**Comment by fazalmajid** [comment]
The error means two ping measurements were recorded for the same time slot. One way I could see this happening is if the interval is short (IIRC yours is 10 seconds). The default ping timeout in pingwatch is 5 seconds, so a timeout could easily push the ping measurement (timeout in this case) in the same time slot as the next scheduled ping.

I fixed this by forcing the second value to override the first one.
