### ISSUE TITLE
Feature Request: improve the legend again

### ISSUE THREAD

**Issue by aslmx** [fazalmajid/pingwatch#8]
Hi Fazal,
after running pingwatch for quite some time now and occasionally checking it's result, I wanted to 1. thank you again for this awesome tool. It still helps me. 
And 2. I'm still sometimes struggling to understand the data that is shown.

The colors of the different ping destinations are similar. Maybe it is my bad vision, but some are hard to differentiate. I attached a screenshot with 4 destinations in 2 groups which look similar to me (red and blue group, red and blue do not have any meaning)

![pingwatch_Screenshot_2020-10-23_08-09-00](https://user-images.githubusercontent.com/13053017/96963807-9e521300-1509-11eb-99d4-969fde500f71.png)

Basically i have two needs
1. sometimes I want to see the long term result for one destination 
2. or i want to know the destination of a strange line

For # 1: 
Does the framework that is used allow to highlight (ie. bold print it) just the one graph line of a data set when you hover it's legend entry? So i could e.g. hover google.com and it would just print the line for google.com a bit more strong than the others.

For # 2: 
When i see some line that looks weird and i hover it, it gets highlighted, i.e. printed bolder than the other ones. Can the corresponding legend entry be highlighted as well? It just takes a bit of zooming or carefully reading the y-axis value to find out which of the two similar-color-hosts is the offending one, but it could be even easier if the legend entry was highlighted.

Thanks for your considerations.
(and again for the tool so far :) )

**Comment by fazalmajid** [comment]
It's not you, [Dygraph](https://dygraphs.com)'s default color selection is not ideal in terms of separation (not very saturated, and poorly demarcated in hue). I'm sure it's doable but it will require doing some custom JavaScript work, along with highlighting the time series you are hovering about.

**Comment by fazalmajid** [comment]
The dygraphs documentation claims  the colors are automatically chosen equidistantly on a color wheel but I don't see that happening. In the meantime, it's very easy to highlight the currently active time series in yellow in the legend, so I've done that in 160696a. The yellow is a bit garish, if you have a more tasteful color or style recommendation, I'm all ears.

**Comment by fazalmajid** [comment]
Also, did you know you can zoom in to a specific vertical range, not just horizontal, e.g. to isolate the pings in your chart < 20ms from the others? Just select with an upward movement using your mouse.

**Comment by aslmx** [comment]
Good Morning!
Thanks a lot!

> Also, did you know you can zoom in to a specific vertical range, not just horizontal, e.g. to isolate the pings in your chart < 20ms from the others? Just select with an upward movement using your mouse.

No, I actually never tried that. Thanks.

> The yellow is a bit garish, if you have a more tasteful color or style recommendation, I'm all ears.

Yellow is not my favourite colour either, but it really is a highlight now - fine for me.

I experimented a little with the developer console. While I can live fine with #ffff66, maybe a very light gray is fine, too? 
I tried with #dddddd and it looks okay. #eeeeee is already too light and #cccccc too dark.
When using the default yellow, I liked it with a padding. The more (e.g. 10px) the better the highlight, but of course it starts to over float the other values, so it might not be optimal default behaviour. 5px was okay.


So # 2 is now fixed for me. When i select a line, its legend entry is clearly visible now. 
Hovering the legend entry and highlight the line (# 1) would be very cool to have, too - if that is possible?

Btw: as far as I can tell, it seems to me all the static stuff is build into the go binary, right? At least if I move the built library somewhere else, it doesn't even complain about the missing sqlite. Anyway: does it make sense to some how make it possible to include external css? Maybe use a specific style sheet when a style.css file exists in the binaries folder? This way it could run as a standalone binary, but still allow easy modification.

Thanks a lot again!

**Comment by fazalmajid** [comment]
Yes, the HTML, CSS and JS are compiled into the pingwatch executable so it's fully self-contained, using the [statik](https://github.com/rakyll/statik) tool. Just install statik, then run `go generate` before calling `go build`. It will generate the file `statik.go` that has a compressed version of those assets.

How comfortable are you with git? Wouldn't it be easier for you to make your own branch with the CSS changes you want and bake them into pingwatch?

**Comment by aslmx** [comment]
> How comfortable are you with git?
I'm fairly new. I know the basics. 

>  Wouldn't it be easier for you to make your own branch with the CSS changes you want and bake them into pingwatch?
By "bake them into pingwatch" you mean to change the values i mentioned and then send a PR?
I can do that when i have some time.

If you mean to change the stuff necessary for # 1 (hovering the legend and make the corresponding graph line to highlight), i have no idea and would probably need to spend some hours to get into the graph library you use.

**Comment by fazalmajid** [comment]
I meant the color or style changes.

Making the legend interactive would require some custom JS work, and is not a trivial change.

**Comment by aslmx** [comment]
so i commited my suggestions. Feel free to merge if you like :) 
I also had a look into dygraphs documentation. But as a non-software-engineer i'm a little overchallenged. I would have looked for some callback if a legend gets highlighted, but i couldn't find it :-(

**Comment by fazalmajid** [comment]
OK, I added the ability to highlight a time series by hovering over the legend (the colored label only, not the ping value). I had written code to make it go away when you stop hovering, but that makes for a slightly jarring user experience, so it will stick until you hover on something else (another legend or in the graph), or if you have autoscroll enabled, a new update arrives. The ping value displayed in the legend when you hover is the most recent one in the current zoom selection.

**Comment by aslmx** [comment]
Thanks a lot! 
This is exactly how I wanted/need it!
Edit: just had a brief view over the diff... Really does not look like a trivial change! Thanks even more!

**Comment by fazalmajid** [comment]
> Really does not look like a trivial change!

Not as much as the rabbit hole of automatically choosing contrasting colors for the data series, including amazing but way too complex to implement solutions like [Palettailor](https://arxiv.org/pdf/2009.02969.pdf)
